/* The following code was generated by JFlex 1.7.0-SNAPSHOT tweaked for IntelliJ platform */

/*
 * Copyright 2000-2008 JetBrains s.r.o.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.jetbrains.plugins.scala.lang.scaladoc.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import org.jetbrains.plugins.scala.lang.scaladoc.lexer.docsyntax.*;
import org.jetbrains.plugins.scala.lang.lexer.ScalaTokenTypes;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0-SNAPSHOT
 * from the specification file <tt>scaladoc.flex</tt>
 */
public class _ScalaDocLexer implements FlexLexer, ScalaDocTokenType, ScalaTokenTypes {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT_DATA_START = 2;
  public static final int COMMENT_DATA = 4;
  public static final int TAG_DOC_SPACE = 6;
  public static final int PARAM_TAG_DOC_SPACE = 8;
  public static final int PARAM_THROWS_TAG_DOC_SPACE = 10;
  public static final int PARAM_TAG_SPACE = 12;
  public static final int DOC_TAG_VALUE = 14;
  public static final int PARAM_DOC_TAG_VALUE = 16;
  public static final int PARAM_DOC_THROWS_TAG_VALUE = 18;
  public static final int DOC_TAG_VALUE_IN_PAREN = 20;
  public static final int DOC_TAG_VALUE_IN_LTGT = 22;
  public static final int INLINE_TAG_NAME = 24;
  public static final int INLINE_DOC_TAG_VALUE = 26;
  public static final int INLINE_TAG_DOC_SPACE = 28;
  public static final int CODE_LINK_INNER = 30;
  public static final int CODE_BAD_LINK = 32;
  public static final int HTTP_LINK_INNER = 34;
  public static final int DOC_TAG_VALUE_SPACE = 36;
  public static final int COMMENT_INNER_CODE = 38;
  public static final int INNER_CODE_WHITESPACE = 40;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7, 
     8,  8,  9,  9, 10, 10,  6,  6, 11, 11, 12, 12, 13, 13, 14, 14, 
    15, 15,  6,  6, 16, 16, 17, 17, 18, 18
  };

  /** 
   * Translates characters to character classes
   * Chosen bits are [12, 6, 3]
   * Total runtime size is 14832 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[(ZZ_CMAP_Y[(ZZ_CMAP_Z[ch>>9]<<6)|((ch>>3)&0x3f)]<<3)|(ch&0x7)];
  }

  /* The ZZ_CMAP_Z table has 2176 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1"+
    "\20\5\21\1\22\1\23\1\24\1\21\14\25\1\26\50\25\1\27\2\25\1\30\1\31\1\32\1\33"+
    "\25\25\1\34\20\21\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\21\1\44\1\45\1\46\1"+
    "\21\1\47\2\21\1\50\4\21\1\25\1\51\1\52\5\21\2\25\1\53\31\21\1\25\1\54\1\21"+
    "\1\55\40\21\1\56\17\21\1\57\1\60\1\61\1\62\13\21\1\63\10\21\123\25\1\64\7"+
    "\25\1\65\1\66\37\21\1\25\1\66\u0582\21\1\67\u017f\21");

  /* The ZZ_CMAP_Y table has 3584 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\1\1\1\0\1\2\1\3\1\4\1\5\1\6\1\7\2\10\1\11\1\12\1\13\1\14\1\15\1\16\3"+
    "\0\1\17\1\20\1\21\1\22\2\10\1\23\3\10\1\23\71\10\1\24\1\10\1\25\1\26\1\27"+
    "\1\30\2\26\16\0\1\31\1\17\1\32\1\33\2\10\1\34\11\10\1\35\21\10\1\36\1\37\23"+
    "\10\1\26\1\40\3\10\1\23\1\41\1\40\4\10\1\42\1\43\4\0\1\44\1\45\1\26\3\10\2"+
    "\46\1\26\1\47\1\50\1\0\1\51\5\10\1\52\3\0\1\53\1\54\13\10\1\55\1\44\1\56\1"+
    "\57\1\0\1\60\1\26\1\61\1\62\3\10\3\0\1\63\12\10\1\64\1\0\1\65\1\26\1\0\1\66"+
    "\3\10\1\52\1\67\1\22\2\10\1\64\1\70\1\71\1\72\2\26\3\10\1\73\10\26\1\74\1"+
    "\27\6\26\1\75\2\0\1\76\1\77\6\10\1\100\2\0\1\101\1\10\1\102\1\0\2\40\1\103"+
    "\1\104\1\105\2\10\1\74\1\106\1\107\1\110\1\111\1\61\1\112\1\102\1\0\1\113"+
    "\1\50\1\103\1\114\1\105\2\10\1\74\1\115\1\116\1\117\1\120\1\121\1\122\1\123"+
    "\1\0\1\124\1\26\1\103\1\35\1\34\2\10\1\74\1\125\1\107\1\44\1\126\1\127\1\26"+
    "\1\102\1\0\1\41\1\26\1\103\1\104\1\105\2\10\1\74\1\125\1\107\1\110\1\120\1"+
    "\123\1\112\1\102\1\0\1\41\1\26\1\130\1\131\1\132\1\133\1\134\1\131\1\10\1"+
    "\135\1\136\1\137\1\140\1\26\1\123\1\0\1\26\1\41\1\103\1\31\1\74\2\10\1\74"+
    "\1\141\1\142\1\143\1\137\1\144\1\25\1\102\1\0\2\26\1\145\1\31\1\74\2\10\1"+
    "\74\1\141\1\107\1\143\1\137\1\144\1\32\1\102\1\0\1\146\1\26\1\145\1\31\1\74"+
    "\4\10\1\147\1\143\1\150\1\61\1\26\1\102\1\0\1\26\1\37\1\145\1\10\1\23\1\37"+
    "\2\10\1\34\1\151\1\23\1\152\1\153\1\0\2\26\1\154\1\26\1\40\5\10\1\155\1\156"+
    "\1\157\1\76\1\0\1\160\4\26\1\161\1\162\1\163\1\40\1\164\1\165\1\155\1\166"+
    "\1\167\1\170\1\0\1\171\4\26\1\127\2\26\1\160\1\0\1\160\1\172\1\173\1\10\1"+
    "\40\3\10\1\27\1\43\1\0\1\143\1\174\1\0\1\43\3\0\1\47\1\175\7\26\5\10\1\52"+
    "\1\0\1\176\1\0\1\160\1\64\1\177\1\200\1\201\1\202\1\10\1\203\1\204\1\0\1\170"+
    "\4\10\1\35\1\21\5\10\1\205\51\10\1\132\1\23\1\132\5\10\1\132\4\10\1\132\1"+
    "\23\1\132\1\10\1\23\7\10\1\132\10\10\1\206\4\26\2\10\2\26\12\10\1\27\1\26"+
    "\1\40\114\10\1\104\2\10\1\40\2\10\1\46\11\10\1\131\1\127\1\26\1\10\1\31\1"+
    "\207\1\26\2\10\1\207\1\26\2\10\1\210\1\26\1\10\1\31\1\211\1\26\6\10\1\212"+
    "\3\0\1\213\1\214\1\0\1\160\3\26\1\215\1\0\1\160\13\10\1\26\5\10\1\216\10\10"+
    "\1\217\1\26\3\10\1\27\1\0\1\2\1\0\1\2\1\123\1\0\3\10\1\217\1\27\1\26\5\10"+
    "\1\113\2\0\1\54\1\160\1\0\1\160\4\26\2\10\1\157\1\2\6\10\1\174\1\76\3\0\1"+
    "\110\1\0\1\160\1\0\1\160\1\42\13\26\1\220\5\10\1\212\1\0\1\220\1\113\1\0\1"+
    "\160\1\26\1\221\1\2\1\26\1\222\3\10\1\101\1\201\1\0\1\66\4\10\1\64\1\0\1\2"+
    "\1\26\4\10\1\212\2\0\1\26\1\0\1\223\1\0\1\66\3\10\1\217\12\26\1\224\2\0\1"+
    "\225\1\226\1\26\30\10\4\0\1\76\2\26\1\75\42\10\2\217\4\10\2\217\1\10\1\227"+
    "\3\10\1\217\6\10\1\31\1\167\1\230\1\27\1\231\1\113\1\10\1\27\1\230\1\27\1"+
    "\26\1\221\3\26\1\232\1\26\1\42\1\127\1\26\1\233\1\26\1\47\1\234\1\41\1\42"+
    "\2\26\1\10\1\27\3\10\1\46\2\26\1\0\1\47\1\235\1\0\1\236\1\26\1\237\1\37\1"+
    "\151\1\240\1\30\1\241\1\10\1\242\1\243\1\244\2\26\5\10\1\127\116\26\5\10\1"+
    "\23\5\10\1\23\20\10\1\27\1\245\1\246\1\26\4\10\1\35\1\21\7\10\1\42\1\26\1"+
    "\61\2\10\1\23\1\26\10\23\4\0\5\26\1\42\72\26\1\243\3\26\1\40\1\203\1\240\1"+
    "\27\1\40\11\10\1\23\1\247\1\40\12\10\1\205\1\243\4\10\1\217\1\40\12\10\1\23"+
    "\2\26\3\10\1\46\6\26\170\10\1\217\11\26\71\10\1\27\6\26\21\10\1\27\10\26\5"+
    "\10\1\217\41\10\1\27\2\10\1\0\1\246\2\26\5\10\1\157\1\75\1\250\3\10\1\61\12"+
    "\10\1\160\3\26\1\42\1\10\1\37\14\10\1\251\1\113\1\26\1\10\1\46\11\26\1\10"+
    "\1\252\1\253\2\10\1\52\2\26\1\127\6\10\1\113\1\26\1\66\5\10\1\212\1\0\1\47"+
    "\1\26\1\0\1\160\2\0\1\66\1\50\1\0\1\66\2\10\1\64\1\170\2\10\1\157\1\0\1\2"+
    "\1\26\3\10\1\27\1\77\5\10\1\52\1\0\1\236\1\42\1\0\1\160\4\26\5\10\1\101\1"+
    "\76\1\26\1\253\1\254\1\0\1\160\2\10\1\23\1\255\6\10\1\200\1\256\1\216\2\26"+
    "\1\257\1\10\1\52\1\260\1\26\3\261\1\26\2\23\22\26\4\10\1\52\1\262\1\0\1\160"+
    "\64\10\1\113\1\26\2\10\1\23\1\263\5\10\1\113\40\26\55\10\1\217\15\10\1\25"+
    "\4\26\1\23\1\26\1\263\1\264\1\10\1\74\1\23\1\167\1\265\15\10\1\25\3\26\1\263"+
    "\54\10\1\217\2\26\10\10\1\37\6\10\5\26\1\10\1\27\2\0\2\26\1\76\1\26\1\134"+
    "\2\26\1\243\3\26\1\41\1\31\20\10\1\266\1\233\1\26\1\0\1\160\1\40\2\10\1\114"+
    "\1\40\2\10\1\46\1\267\12\10\1\23\3\37\1\270\1\271\2\26\1\272\1\10\1\141\2"+
    "\10\1\23\2\10\1\273\1\10\1\217\1\10\1\217\4\26\17\10\1\46\10\26\6\10\1\27"+
    "\20\26\1\274\20\26\3\10\1\27\6\10\1\127\5\26\3\10\1\23\2\26\3\10\1\46\6\26"+
    "\3\10\1\217\4\10\1\113\1\10\1\240\5\26\23\10\1\217\1\0\1\160\52\26\1\217\1"+
    "\74\4\10\1\35\1\275\2\10\1\217\25\26\2\10\1\217\1\26\3\10\1\25\10\26\7\10"+
    "\1\267\10\26\1\276\1\75\1\141\1\40\2\10\1\113\1\117\4\26\3\10\1\27\20\26\6"+
    "\10\1\217\1\26\2\10\1\217\1\26\2\10\1\46\21\26\11\10\1\127\66\26\1\222\6\10"+
    "\1\0\1\76\3\26\1\123\1\0\2\26\1\222\5\10\1\0\1\277\2\26\3\10\1\127\1\0\1\160"+
    "\1\222\3\10\1\157\1\0\1\143\1\0\10\26\1\222\5\10\1\52\1\0\1\300\1\26\1\0\1"+
    "\160\24\26\5\10\1\52\1\0\1\26\1\0\1\160\46\26\55\10\1\23\22\26\14\10\1\46"+
    "\63\26\5\10\1\23\72\26\7\10\1\127\130\26\10\10\1\27\1\26\1\101\4\0\1\76\1"+
    "\26\1\61\1\222\1\10\14\26\1\25\153\26\1\301\1\302\2\0\1\303\1\2\3\26\1\304"+
    "\22\26\1\305\67\26\12\10\1\31\10\10\1\31\1\306\1\307\1\10\1\310\1\141\7\10"+
    "\1\35\1\311\2\31\3\10\1\312\1\167\1\37\1\74\51\10\1\217\3\10\1\74\2\10\1\205"+
    "\3\10\1\205\2\10\1\31\3\10\1\31\2\10\1\23\3\10\1\23\3\10\1\74\3\10\1\74\2"+
    "\10\1\205\1\313\6\0\1\141\3\10\1\161\1\40\1\205\1\314\1\237\1\315\1\161\1"+
    "\227\1\161\2\205\1\122\1\10\1\34\1\10\1\113\1\316\1\34\1\10\1\113\50\26\32"+
    "\10\1\23\5\26\106\10\1\27\1\26\33\10\1\217\74\26\1\121\3\26\14\0\20\26\36"+
    "\0\2\26");

  /* The ZZ_CMAP_A table has 1656 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\11\23\1\2\1\1\1\36\1\37\1\1\6\23\4\0\1\2\1\6\1\25\1\7\1\35\2\6\1\27\1\46"+
    "\1\47\1\30\1\6\1\31\1\10\1\5\1\14\12\3\1\12\1\0\1\6\1\34\2\6\1\50\22\4\1\32"+
    "\1\13\1\45\1\11\1\24\1\26\1\15\2\17\1\54\1\55\1\56\1\4\1\41\1\57\2\4\1\17"+
    "\1\53\1\60\1\51\1\43\1\4\1\16\1\44\1\42\1\17\1\4\1\52\1\4\1\17\1\4\1\33\1"+
    "\22\1\40\1\6\6\23\1\20\2\23\2\0\4\4\4\0\1\4\2\0\1\23\7\0\1\4\4\0\1\4\5\0\7"+
    "\4\1\0\2\4\4\0\4\4\16\0\5\4\7\0\1\4\1\0\1\4\1\0\5\4\1\0\2\4\6\0\1\4\1\0\3"+
    "\4\1\0\1\4\1\0\4\4\1\0\13\4\1\0\3\4\1\0\5\23\2\0\6\4\1\0\7\4\1\0\1\4\15\0"+
    "\1\4\1\0\15\23\1\0\1\23\1\0\2\23\1\0\2\23\1\0\1\23\3\4\5\0\5\23\6\0\1\4\4"+
    "\0\3\23\5\0\3\4\7\23\4\0\2\4\1\23\13\4\1\0\1\4\7\23\2\4\2\23\1\0\4\23\2\4"+
    "\2\23\3\4\2\0\1\4\7\0\1\23\1\4\1\23\6\4\3\23\2\0\11\4\3\23\1\4\6\0\2\23\6"+
    "\4\4\23\2\4\2\0\2\23\1\4\11\23\1\4\3\23\1\4\5\23\2\0\1\4\3\23\4\0\1\4\1\0"+
    "\6\4\4\0\13\23\1\0\4\23\6\4\3\23\1\4\2\23\1\4\7\23\2\4\2\23\2\0\2\23\1\0\3"+
    "\23\1\0\10\4\2\0\2\4\2\0\6\4\1\0\1\4\3\0\4\4\2\0\1\23\1\4\7\23\2\0\2\23\2"+
    "\0\3\23\1\4\5\0\2\4\1\0\5\4\4\0\3\4\4\0\2\4\1\0\2\4\1\0\2\4\1\0\2\4\2\0\1"+
    "\23\1\0\5\23\4\0\2\23\2\0\3\23\3\0\1\23\7\0\4\4\1\0\1\4\7\0\4\23\3\4\1\23"+
    "\2\0\1\4\1\0\2\4\1\0\3\4\2\23\1\0\3\23\2\0\1\4\11\0\1\23\1\4\1\0\6\4\3\0\3"+
    "\4\1\0\4\4\3\0\2\4\1\0\1\4\1\0\2\4\3\0\2\4\3\0\2\4\4\0\5\23\3\0\3\23\1\0\4"+
    "\23\2\0\1\4\6\0\1\23\4\4\1\0\5\4\3\0\1\4\7\23\1\0\2\23\5\0\2\23\3\0\2\23\1"+
    "\0\3\4\1\0\2\4\5\0\3\4\2\0\1\4\3\23\1\0\4\23\1\4\1\0\4\4\1\0\1\4\4\0\1\23"+
    "\4\0\6\23\1\0\1\23\3\0\2\23\4\0\1\4\1\23\2\4\7\23\4\0\10\4\3\23\7\0\2\4\1"+
    "\0\1\4\2\0\2\4\1\0\1\4\2\0\1\4\6\0\4\4\1\0\3\4\1\0\1\4\1\0\1\4\2\0\2\4\1\0"+
    "\3\4\2\23\1\0\2\23\1\4\2\0\5\4\1\0\1\4\1\0\6\23\2\0\2\23\2\0\4\4\5\0\1\23"+
    "\1\0\1\23\1\0\1\23\4\0\2\23\5\4\3\23\6\0\1\23\1\0\7\23\1\4\2\23\4\4\3\23\1"+
    "\4\3\23\2\4\7\23\3\4\4\23\5\4\14\23\1\4\1\23\3\4\1\0\7\4\2\0\3\23\2\4\3\23"+
    "\3\0\2\4\2\23\4\0\1\4\1\0\2\23\4\0\4\4\10\23\3\0\1\4\3\0\2\4\1\23\5\0\3\23"+
    "\2\0\1\4\1\23\1\4\5\0\6\4\2\0\5\23\3\4\3\0\10\23\5\4\2\23\3\0\3\4\3\23\1\0"+
    "\5\23\4\4\1\23\4\4\3\23\2\4\2\0\1\4\1\0\1\4\1\0\1\4\1\0\1\4\2\0\3\4\1\0\6"+
    "\4\2\0\2\4\2\21\5\23\5\0\1\4\5\0\6\23\1\0\1\23\3\0\4\23\11\0\1\4\4\0\1\4\1"+
    "\0\5\4\2\0\1\4\1\0\4\4\1\0\3\4\2\0\4\4\5\0\5\4\4\0\1\4\4\0\4\4\3\23\2\4\5"+
    "\0\2\23\2\0\3\4\6\23\1\0\2\4\2\0\4\4\1\0\2\4\1\23\3\4\1\23\4\4\1\23\10\4\2"+
    "\23\4\0\1\4\1\23\4\0\1\23\5\4\2\23\3\0\3\4\4\0\3\4\2\23\2\0\6\4\1\0\3\23\1"+
    "\0\2\23\5\0\5\4\5\0\1\4\1\23\3\4\1\0\2\4\1\0\7\4\2\0\1\23\6\0\2\4\2\0\3\4"+
    "\3\0\2\4\3\0\2\4\2\0\3\23\4\0\3\4\1\0\2\4\1\0\1\4\5\0\1\23\2\0\1\4\3\0\1\4"+
    "\2\0\2\4\3\23\1\0\2\23\1\0\3\23\2\0\1\23\2\0\1\23\4\4\10\0\5\23\3\0\6\23\2"+
    "\0\3\23\2\0\4\23\4\0\3\23\5\0\1\4\2\0\2\4\2\0\4\4\1\0\4\4\1\0\1\4\1\0\6\4"+
    "\2\0\5\4\1\0\4\4\1\0\4\4\2\0\2\23\1\0\1\4\1\0\1\4\5\0\1\4\1\0\1\4\1\0\3\4"+
    "\1\0\3\4\1\0\3\4");

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\23\0\3\1\1\2\1\3\1\4\1\2\1\5\5\2"+
    "\1\6\3\2\1\7\1\10\1\11\1\1\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\3\21\2\1\1\22"+
    "\1\23\2\22\2\1\1\24\1\1\1\7\1\25\1\26"+
    "\3\27\3\1\1\30\2\31\2\32\1\0\1\33\1\0"+
    "\1\34\1\35\1\36\1\37\2\0\1\40\1\41\4\42"+
    "\1\21\2\0\1\21\1\43\1\22\2\0\1\22\1\44"+
    "\1\27\3\0\1\27\1\0\1\45\1\46\1\0\1\47"+
    "\1\50\3\42\1\0\1\21\1\0\1\22\1\0\1\51"+
    "\1\27\1\52\2\0\3\42\2\43\3\0\3\42\1\51"+
    "\1\53\1\0\1\42\1\54\1\42\1\55\1\0\1\56";

  private static int [] zzUnpackAction() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\u0126\0\u0157"+
    "\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c\0\u027d\0\u02ae\0\u02df"+
    "\0\u0310\0\u0341\0\u0372\0\u0372\0\u03a3\0\u03d4\0\u0372\0\u0405"+
    "\0\u0372\0\u0436\0\u0372\0\u0467\0\u03d4\0\u0498\0\u04c9\0\u04fa"+
    "\0\u052b\0\u055c\0\u058d\0\u05be\0\u05ef\0\u0620\0\u0651\0\u04c9"+
    "\0\u0682\0\u06b3\0\u06e4\0\u0715\0\u0372\0\u0372\0\u0372\0\u0746"+
    "\0\u0777\0\u07a8\0\u0777\0\u07d9\0\u080a\0\u0372\0\u083b\0\u086c"+
    "\0\u089d\0\u08ce\0\u0372\0\u08ff\0\u0930\0\u0372\0\u0961\0\u0992"+
    "\0\u09c3\0\u09f4\0\u0a25\0\u0a56\0\u058d\0\u0a87\0\u0372\0\u03d4"+
    "\0\u0372\0\u0ab8\0\u0ae9\0\u0372\0\u03d4\0\u0372\0\u0b1a\0\u0372"+
    "\0\u0b4b\0\u0b7c\0\u0bad\0\u0bde\0\u0372\0\u0c0f\0\u0c40\0\u0c71"+
    "\0\u0ca2\0\u0cd3\0\u07d9\0\u0d04\0\u0372\0\u0372\0\u0d35\0\u08ce"+
    "\0\u0d66\0\u0d97\0\u0dc8\0\u0df9\0\u0e2a\0\u0a56\0\u0e5b\0\u0e8c"+
    "\0\u0ebd\0\u0372\0\u0eee\0\u0f1f\0\u0372\0\u0f50\0\u0f81\0\u0fb2"+
    "\0\u0fe3\0\u0777\0\u07d9\0\u089d\0\u1014\0\u0a25\0\u0372\0\u1045"+
    "\0\u0372\0\u1076\0\u10a7\0\u10d8\0\u1109\0\u113a\0\u08ce\0\u0a56"+
    "\0\u116b\0\u119c\0\u11cd\0\u11fe\0\u122f\0\u1260\0\u0a56\0\u0372"+
    "\0\u1291\0\u12c2\0\u0c0f\0\u12f3\0\u0372\0\u1324\0\u0c0f";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\14\24\1\25\13\24\1\26\30\24\1\27\2\30\6\27"+
    "\1\31\6\27\2\24\2\27\1\32\1\27\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\24\1\30"+
    "\5\27\1\43\2\27\1\44\11\27\1\30\1\45\6\27"+
    "\1\31\6\27\2\24\2\27\1\32\1\27\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\46\1\42\1\24\1\45"+
    "\5\27\1\43\13\27\1\24\2\47\25\24\1\26\1\24"+
    "\1\50\4\24\1\47\22\24\1\51\1\52\25\24\1\26"+
    "\6\24\1\52\22\24\1\51\1\53\25\24\1\26\6\24"+
    "\1\53\51\24\1\26\30\24\1\27\2\51\3\54\1\27"+
    "\1\55\5\27\3\54\2\24\2\27\1\54\3\27\1\35"+
    "\1\56\1\54\2\27\1\54\1\24\1\51\1\27\5\54"+
    "\1\57\2\27\10\54\4\24\1\60\1\24\7\61\3\62"+
    "\2\24\1\63\1\24\1\62\1\24\1\64\1\24\1\61"+
    "\3\24\1\61\1\60\3\24\2\62\1\60\1\62\3\24"+
    "\1\61\1\62\1\60\3\62\1\60\2\62\4\24\1\65"+
    "\1\66\7\67\3\70\2\24\1\71\1\24\1\70\1\24"+
    "\1\72\1\24\1\67\3\24\1\67\1\65\3\24\2\70"+
    "\1\65\1\70\3\24\1\67\1\70\1\65\3\70\1\65"+
    "\2\70\1\24\2\30\3\54\7\24\3\54\4\24\1\54"+
    "\3\24\1\26\1\56\1\54\2\24\1\54\1\24\1\30"+
    "\1\24\5\54\1\24\1\73\1\24\10\54\30\24\1\26"+
    "\17\24\1\74\10\24\40\75\1\76\20\75\1\24\2\77"+
    "\25\24\1\26\6\24\1\77\1\76\24\24\1\100\1\66"+
    "\7\101\3\102\2\24\1\103\1\24\1\102\1\24\1\104"+
    "\1\24\1\101\3\24\1\101\1\100\3\24\2\102\1\100"+
    "\1\102\1\105\2\24\1\101\1\102\1\100\3\102\1\100"+
    "\2\102\1\24\1\106\26\24\1\26\14\24\1\105\13\24"+
    "\1\107\2\51\15\107\2\24\6\107\1\110\5\107\1\24"+
    "\1\51\21\107\1\111\1\30\16\111\2\0\14\111\2\0"+
    "\1\112\20\111\111\0\1\113\44\0\1\114\13\0\1\115"+
    "\31\0\2\30\34\0\1\30\45\0\1\116\63\0\1\117"+
    "\62\0\1\120\61\0\1\121\61\0\1\122\14\0\1\123"+
    "\44\0\1\41\30\0\1\124\10\0\3\124\4\0\1\124"+
    "\10\0\1\124\3\0\4\124\4\0\10\124\45\0\1\125"+
    "\17\0\1\126\10\0\3\126\4\0\1\126\10\0\1\126"+
    "\3\0\1\126\1\127\1\130\1\126\4\0\3\126\1\131"+
    "\4\126\2\0\1\45\34\0\1\45\55\0\1\46\25\0"+
    "\2\47\34\0\1\47\22\0\2\51\34\0\1\51\22\0"+
    "\1\51\1\52\34\0\1\52\22\0\1\51\1\53\34\0"+
    "\1\53\24\0\3\54\7\0\3\54\4\0\1\54\5\0"+
    "\1\54\2\0\1\54\3\0\5\54\3\0\10\54\3\0"+
    "\2\60\10\0\4\60\2\0\1\60\1\132\10\0\1\60"+
    "\3\0\4\60\4\0\10\60\6\0\12\61\2\0\1\61"+
    "\1\0\1\61\3\0\1\61\3\0\1\61\4\0\2\61"+
    "\1\0\1\61\3\0\2\61\1\0\3\61\1\0\2\61"+
    "\3\0\2\60\1\0\7\61\3\62\1\60\1\0\1\61"+
    "\1\60\1\62\3\0\1\61\3\0\1\61\1\60\3\0"+
    "\2\62\1\60\1\62\3\0\1\61\1\62\1\60\3\62"+
    "\1\60\2\62\1\133\1\0\11\133\1\134\4\133\2\0"+
    "\3\133\1\0\1\135\32\133\3\0\2\65\1\136\7\0"+
    "\4\65\2\0\1\65\1\137\10\0\1\65\3\0\4\65"+
    "\4\0\10\65\5\0\1\136\12\67\2\0\1\67\1\0"+
    "\1\67\3\0\1\67\3\0\1\67\4\0\2\67\1\0"+
    "\1\67\3\0\2\67\1\0\3\67\1\0\2\67\3\0"+
    "\2\65\1\136\7\67\3\70\1\65\1\0\1\67\1\65"+
    "\1\70\3\0\1\67\3\0\1\67\1\65\3\0\2\70"+
    "\1\65\1\70\3\0\1\67\1\70\1\65\3\70\1\65"+
    "\2\70\6\0\12\67\2\0\1\67\1\0\1\67\3\0"+
    "\1\67\3\0\1\67\4\0\2\67\1\0\1\67\3\0"+
    "\2\67\1\0\3\67\1\0\2\67\1\140\1\0\11\140"+
    "\1\141\4\140\2\0\3\140\1\0\1\142\32\140\4\0"+
    "\1\143\10\0\3\143\4\0\1\143\10\0\1\143\3\0"+
    "\4\143\4\0\10\143\40\75\1\0\20\75\1\0\2\77"+
    "\34\0\1\77\24\0\2\100\1\136\7\0\4\100\2\0"+
    "\1\100\1\144\10\0\1\100\3\0\4\100\1\145\3\0"+
    "\10\100\5\0\1\136\12\101\2\0\1\101\1\0\1\101"+
    "\3\0\1\101\3\0\1\101\4\0\2\101\1\0\1\101"+
    "\1\145\2\0\2\101\1\0\3\101\1\0\2\101\3\0"+
    "\2\100\1\136\7\101\3\102\1\100\1\0\1\101\1\100"+
    "\1\102\3\0\1\101\3\0\1\101\1\100\3\0\2\102"+
    "\1\100\1\102\1\145\2\0\1\101\1\102\1\100\3\102"+
    "\1\100\2\102\6\0\12\101\2\0\1\101\1\0\1\101"+
    "\3\0\1\101\3\0\1\101\4\0\2\101\1\0\1\101"+
    "\3\0\2\101\1\0\3\101\1\0\2\101\1\146\1\0"+
    "\11\146\1\147\4\146\2\0\3\146\1\0\1\150\32\146"+
    "\1\0\2\106\34\0\1\106\61\0\1\151\50\0\1\152"+
    "\57\0\1\153\72\0\1\154\52\0\1\155\31\0\1\156"+
    "\10\0\3\156\4\0\1\156\10\0\1\156\3\0\4\156"+
    "\4\0\10\156\3\0\3\124\2\0\1\124\1\0\1\124"+
    "\2\0\3\124\4\0\1\124\10\0\1\124\3\0\4\124"+
    "\4\0\10\124\3\0\3\126\2\0\1\126\1\0\1\126"+
    "\2\0\3\126\4\0\1\126\10\0\1\126\3\0\4\126"+
    "\4\0\10\126\3\0\3\126\2\0\1\126\1\0\1\126"+
    "\2\0\3\126\4\0\1\126\10\0\1\126\3\0\1\157"+
    "\1\126\1\130\1\126\4\0\10\126\3\0\3\126\2\0"+
    "\1\126\1\0\1\126\2\0\1\160\2\126\4\0\1\126"+
    "\10\0\1\126\3\0\4\126\4\0\10\126\3\0\3\126"+
    "\2\0\1\126\1\0\1\126\2\0\3\126\4\0\1\126"+
    "\10\0\1\126\3\0\4\126\4\0\4\126\1\161\3\126"+
    "\3\0\2\60\1\0\7\61\3\62\1\60\1\0\1\162"+
    "\1\60\1\62\3\0\1\61\3\0\1\61\1\60\3\0"+
    "\2\62\1\60\1\62\3\0\1\61\1\62\1\60\3\62"+
    "\1\60\2\62\1\133\1\0\11\133\1\134\12\133\1\163"+
    "\32\133\3\0\2\65\1\136\7\67\3\70\1\65\1\0"+
    "\1\164\1\65\1\70\3\0\1\67\3\0\1\67\1\65"+
    "\3\0\2\70\1\65\1\70\3\0\1\67\1\70\1\65"+
    "\3\70\1\65\2\70\1\140\1\0\11\140\1\141\12\140"+
    "\1\165\32\140\5\0\1\136\56\0\3\143\2\0\1\143"+
    "\1\0\1\143\2\0\3\143\4\0\1\143\10\0\1\143"+
    "\3\0\4\143\4\0\10\143\3\0\2\100\1\136\7\101"+
    "\3\102\1\100\1\0\1\166\1\100\1\102\3\0\1\101"+
    "\3\0\1\101\1\100\3\0\2\102\1\100\1\102\1\145"+
    "\2\0\1\101\1\102\1\100\3\102\1\100\2\102\45\0"+
    "\1\167\13\0\1\146\1\0\11\146\1\147\12\146\1\170"+
    "\32\146\5\0\1\136\37\0\1\145\53\0\1\171\47\0"+
    "\1\172\73\0\1\173\21\0\3\156\2\0\1\156\1\0"+
    "\1\156\2\0\3\156\4\0\1\156\10\0\1\156\3\0"+
    "\4\156\4\0\10\156\3\0\3\126\2\0\1\126\1\0"+
    "\1\126\2\0\1\126\1\174\1\126\4\0\1\126\10\0"+
    "\1\126\3\0\4\126\4\0\10\126\3\0\3\126\2\0"+
    "\1\126\1\0\1\126\2\0\1\126\1\175\1\126\4\0"+
    "\1\126\10\0\1\126\3\0\4\126\4\0\10\126\3\0"+
    "\3\126\2\0\1\126\1\0\1\126\2\0\3\126\4\0"+
    "\1\126\10\0\1\126\3\0\4\126\4\0\5\126\1\176"+
    "\2\126\1\140\1\0\3\140\1\177\5\140\1\141\4\140"+
    "\2\0\3\140\1\0\1\142\32\140\1\146\1\0\3\146"+
    "\1\200\5\146\1\147\4\146\2\0\3\146\1\0\1\150"+
    "\16\146\1\201\13\146\27\0\1\202\73\0\1\203\21\0"+
    "\3\126\2\0\1\126\1\0\1\126\2\0\3\126\4\0"+
    "\1\126\10\0\1\126\3\0\4\126\4\0\1\204\7\126"+
    "\3\0\3\126\2\0\1\126\1\0\1\126\2\0\1\205"+
    "\2\126\4\0\1\126\10\0\1\126\3\0\4\126\4\0"+
    "\10\126\3\0\3\126\2\0\1\126\1\0\1\126\2\0"+
    "\3\126\4\0\1\126\10\0\1\126\3\0\4\126\4\0"+
    "\6\126\1\206\1\126\1\146\1\0\11\146\1\147\4\146"+
    "\2\0\3\146\1\0\1\150\16\146\1\207\13\146\27\210"+
    "\1\0\31\210\43\0\1\211\20\0\3\126\2\0\1\126"+
    "\1\0\1\126\2\0\3\126\4\0\1\126\10\0\1\126"+
    "\3\0\4\126\4\0\1\126\1\212\6\126\3\0\3\126"+
    "\2\0\1\126\1\0\1\126\2\0\3\126\4\0\1\126"+
    "\10\0\1\126\3\0\4\126\4\0\2\126\1\213\5\126"+
    "\3\0\3\126\2\0\1\126\1\0\1\126\2\0\3\126"+
    "\4\0\1\126\10\0\1\126\3\0\4\126\4\0\7\126"+
    "\1\214\12\0\1\215\31\0\1\216\17\0\3\126\2\0"+
    "\1\126\1\0\1\126\2\0\3\126\4\0\1\126\10\0"+
    "\1\126\3\0\3\126\1\217\4\0\10\126\3\0\3\126"+
    "\2\0\1\126\1\0\1\126\2\0\3\126\4\0\1\126"+
    "\10\0\1\126\3\0\4\126\4\0\4\126\1\213\3\126"+
    "\12\0\1\215\46\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4949];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\22\0\1\10\1\11\2\1\1\11\1\1\1\11\1\1"+
    "\1\11\21\1\3\11\6\1\1\11\4\1\1\11\2\1"+
    "\1\11\10\1\1\11\1\1\1\11\1\1\1\0\1\11"+
    "\1\0\1\11\1\1\1\11\1\1\2\0\1\1\1\11"+
    "\5\1\2\0\2\11\1\1\2\0\3\1\3\0\1\1"+
    "\1\0\1\11\1\1\1\0\1\11\4\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\11\1\1\1\11\2\0\5\1"+
    "\3\0\4\1\1\11\1\0\3\1\1\11\1\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

  private boolean isOddItalicBold = false;;

  public _ScalaDocLexer() {
    this((java.io.Reader)null);
  }

  public boolean checkAhead(char c) {
     if (zzMarkedPos >= zzBuffer.length()) return false;
     return zzBuffer.charAt(zzMarkedPos) == c;
  }

  public void goTo(int offset) {
    zzCurrentPos = zzMarkedPos = zzStartRead = offset;
    zzAtEOF = offset < zzEndRead;
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _ScalaDocLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return DOC_COMMENT_BAD_CHARACTER;
            }
          case 47: break;
          case 2: 
            { yybegin(COMMENT_DATA);
  return DOC_COMMENT_DATA;
            }
          case 48: break;
          case 3: 
            { return DOC_WHITESPACE;
            }
          case 49: break;
          case 4: 
            { return DOC_SUPERSCRIPT_TAG;
            }
          case 50: break;
          case 5: 
            { return DOC_MONOSPACE_TAG;
            }
          case 51: break;
          case 6: 
            { return VALID_DOC_HEADER;
            }
          case 52: break;
          case 7: 
            { return DOC_COMMENT_DATA;
            }
          case 53: break;
          case 8: 
            { return DOC_HEADER;
            }
          case 54: break;
          case 9: 
            { yybegin(COMMENT_DATA);
   return DOC_WHITESPACE;
            }
          case 55: break;
          case 10: 
            { yybegin(COMMENT_DATA); return DOC_WHITESPACE;
            }
          case 56: break;
          case 11: 
            { yybegin(PARAM_DOC_TAG_VALUE); return DOC_COMMENT_DATA;
            }
          case 57: break;
          case 12: 
            { yybegin(PARAM_DOC_THROWS_TAG_VALUE); return DOC_COMMENT_DATA;
            }
          case 58: break;
          case 13: 
            { return DOC_TAG_VALUE_TOKEN;
            }
          case 59: break;
          case 14: 
            { return DOC_TAG_VALUE_SHARP_TOKEN;
            }
          case 60: break;
          case 15: 
            { return DOC_TAG_VALUE_COMMA;
            }
          case 61: break;
          case 16: 
            { yybegin(DOC_TAG_VALUE_IN_PAREN); return DOC_TAG_VALUE_LPAREN;
            }
          case 62: break;
          case 17: 
            { yybegin(DOC_TAG_VALUE_SPACE); return DOC_TAG_VALUE_TOKEN;
            }
          case 63: break;
          case 18: 
            { yybegin(DOC_TAG_VALUE_SPACE);
  return tIDENTIFIER;
            }
          case 64: break;
          case 19: 
            { return tDOT;
            }
          case 65: break;
          case 20: 
            { yybegin(DOC_TAG_VALUE); return DOC_TAG_VALUE_RPAREN;
            }
          case 66: break;
          case 21: 
            { yybegin(COMMENT_DATA); return DOC_INLINE_TAG_END;
            }
          case 67: break;
          case 22: 
            { yybegin(INLINE_DOC_TAG_VALUE);
  return DOC_WHITESPACE;
            }
          case 68: break;
          case 23: 
            { yybegin(CODE_BAD_LINK);
  return tIDENTIFIER;
            }
          case 69: break;
          case 24: 
            { yybegin(COMMENT_DATA);
  return DOC_WHITESPACE;
            }
          case 70: break;
          case 25: 
            { yybegin(COMMENT_DATA); return DOC_COMMENT_DATA;
            }
          case 71: break;
          case 26: 
            { yybegin(COMMENT_INNER_CODE);
  return DOC_INNER_CODE;
            }
          case 72: break;
          case 27: 
            { return DOC_COMMENT_END;
            }
          case 73: break;
          case 28: 
            { return DOC_UNDERLINE_TAG;
            }
          case 74: break;
          case 29: 
            { return DOC_ITALIC_TAG;
            }
          case 75: break;
          case 30: 
            { return DOC_SUBSCRIPT_TAG;
            }
          case 76: break;
          case 31: 
            { yybegin(CODE_LINK_INNER);
  return DOC_LINK_TAG;
            }
          case 77: break;
          case 32: 
            { return DOC_MACROS;
            }
          case 78: break;
          case 33: 
            { yybegin(COMMENT_DATA);
  return DOC_LINK_CLOSE_TAG;
            }
          case 79: break;
          case 34: 
            { yybegin(TAG_DOC_SPACE); return DOC_TAG_NAME;
            }
          case 80: break;
          case 35: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL/*, zzStartRead, zzEndRead - zzStartRead*/, zzMarkedPos, -1);
            { return tIDENTIFIER;
            }
          case 81: break;
          case 36: 
            { yybegin(INLINE_TAG_DOC_SPACE); return DOC_TAG_NAME;
            }
          case 82: break;
          case 37: 
            { yybegin(COMMENT_DATA_START); return DOC_COMMENT_START;
            }
          case 83: break;
          case 38: 
            { return DOC_BOLD_TAG;
            }
          case 84: break;
          case 39: 
            { yybegin(COMMENT_INNER_CODE);
  return DOC_INNER_CODE_TAG;
            }
          case 85: break;
          case 40: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL/*, zzStartRead, zzEndRead - zzStartRead*/, zzStartRead, 1);
            { yybegin(INLINE_TAG_NAME);
  return DOC_INLINE_TAG_START;
            }
          case 86: break;
          case 41: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL/*, zzStartRead, zzEndRead - zzStartRead*/, zzMarkedPos, -2);
            { return tIDENTIFIER;
            }
          case 87: break;
          case 42: 
            { yybegin(COMMENT_DATA);
  return DOC_INNER_CLOSE_CODE_TAG;
            }
          case 88: break;
          case 43: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL/*, zzStartRead, zzEndRead - zzStartRead*/, zzStartRead, 3);
            { if (isOddItalicBold) {
    isOddItalicBold = false;
    yypushback(1);
    return DOC_ITALIC_TAG;
  }
  isOddItalicBold = true;
  return DOC_BOLD_TAG;
            }
          case 89: break;
          case 44: 
            { yybegin(PARAM_TAG_DOC_SPACE); return DOC_TAG_NAME;
            }
          case 90: break;
          case 45: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL/*, zzStartRead, zzEndRead - zzStartRead*/, zzStartRead, 2);
            { yybegin(COMMENT_DATA);
  return DOC_HTTP_LINK_TAG;
            }
          case 91: break;
          case 46: 
            { yybegin(PARAM_THROWS_TAG_DOC_SPACE); return DOC_TAG_NAME;
            }
          case 92: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
